In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv("/content/Automobile_data (1).csv")

In [18]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [19]:
df["normalized-losses"].replace("?",np.nan,inplace=True)

/tmp/ipykernel_2036/1267431917.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].replace("?",np.nan,inplace=True)

In [20]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [21]:
df["normalized-losses"] = pd.to_numeric(
    df["normalized-losses"],
    errors="coerce"
)

m=df["normalized-losses"].mean()
print("Mean of normalized-losses : ",m)
df["normalized-losses"].fillna(m,inplace=True)

Mean of normalized-losses :  122.0

/tmp/ipykernel_2036/1123594234.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].fillna(m,inplace=True)

In [22]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [23]:
#replace ? with null values in "horsepower" column permanently
df["horsepower"].replace("?",np.nan,inplace=True)
#change the datatype of df["horsepower"] column from object to float
#permanently
df["horsepower"]=df["horsepower"].astype("float")

/tmp/ipykernel_2036/33509820.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].replace("?",np.nan,inplace=True)

In [24]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [25]:
df["horsepower"].mean()
print("Mean of horsepower : ",m)
df["horsepower"].fillna(m,inplace=True)

Mean of horsepower :  122.0

/tmp/ipykernel_2036/2103322736.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].fillna(m,inplace=True)

In [26]:
df_num=df.select_dtypes(["int64","float64"])#hold to int and float type data
df_cat=df.select_dtypes(object)#hold object type data

In [27]:
from sklearn.preprocessing import LabelEncoder
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [28]:
df_cat.head()

   make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [29]:
df_new=pd.concat([df_num,df_cat],axis=1) #axis=1 column wise
df_new.head()

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,13495,0,1,0,2,0,0
1,3,122.0,64.1,48.8,130,111.0,21,27,16500,0,1,0,2,0,0
2,1,122.0,65.5,52.4,152,154.0,19,26,16500,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,13950,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,17450,1,1,3,0,0,3

In [30]:
X=df_new.drop("price",axis=1) #apart from price, all columns hold in X variable
Y=df_new["price"] #output variable

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                              random_state=1)

In [40]:
X_train.shape,X_test.shape

((143,), (62,))

In [41]:
Y_train.shape,Y_test.shape

((143,), (62,))

In [33]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [34]:
X_train

array([[ 1.69785729,  0.02383412,  0.12469565, ...,  1.17275014,
        -0.14638501,  0.00639503],
       [-1.42488988,  0.02383412,  0.21756793, ...,  1.17275014,
        -0.14638501, -2.73707423],
       [-0.64420309, -1.38767531, -1.12908013, ..., -2.35784501,
        -0.14638501,  0.00639503],
       ...,
       [ 1.69785729,  0.7123753 ,  2.07501352, ...,  1.17275014,
        -0.14638501,  1.83537454],
       [ 0.91717049, -1.31882119, -1.03620785, ..., -2.35784501,
        -0.14638501,  0.92088479],
       [-0.64420309, -0.52699883, -0.38610189, ..., -0.59254744,
        -0.14638501,  0.00639503]])

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
lr=LinearRegression()

In [37]:
lr.fit(X_train,Y_train)

LinearRegression()

In [38]:
y_pred = lr.predict(X_test)

In [39]:
y_pred[:10]

array([ 6156.30873405,  6881.39391275,  5171.26920617,  6520.51014054,
        9093.39963824, 26361.27296732,  7457.92344044,   853.81331031,
        5152.19300699, 13525.47175298])