In [52]:
import pandas as pd
import numpy as np

In [53]:
df=pd.read_csv("/content/Automobile_data (1).csv")

In [54]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [55]:
df["normalized-losses"].replace("?",np.nan,inplace=True)

/tmp/ipykernel_627/1267431917.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].replace("?",np.nan,inplace=True)

In [56]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [57]:
df["normalized-losses"] = pd.to_numeric(
    df["normalized-losses"],
    errors="coerce"
)

m=df["normalized-losses"].mean()
print("Mean of normalized-losses : ",m)
df["normalized-losses"].fillna(m,inplace=True)

Mean of normalized-losses :  122.0

/tmp/ipykernel_627/1123594234.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].fillna(m,inplace=True)

In [58]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [59]:
#replace ? with null values in "horsepower" column permanently
df["horsepower"].replace("?",np.nan,inplace=True)
#change the datatype of df["horsepower"] column from object to float
#permanently
df["horsepower"]=df["horsepower"].astype("float")

/tmp/ipykernel_627/33509820.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].replace("?",np.nan,inplace=True)

In [60]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [61]:
df["horsepower"].mean()
print("Mean of horsepower : ",m)
df["horsepower"].fillna(m,inplace=True)

Mean of horsepower :  122.0

/tmp/ipykernel_627/2103322736.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].fillna(m,inplace=True)

In [62]:
df_num=df.select_dtypes(["int64","float64"])#hold to int and float type data
df_cat=df.select_dtypes(object)#hold object type data

In [63]:
from sklearn.preprocessing import LabelEncoder
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [64]:
df_cat.head()

   make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [65]:
df_new=pd.concat([df_num,df_cat],axis=1) #axis=1 column wise
df_new.head()

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,13495,0,1,0,2,0,0
1,3,122.0,64.1,48.8,130,111.0,21,27,16500,0,1,0,2,0,0
2,1,122.0,65.5,52.4,152,154.0,19,26,16500,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,13950,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,17450,1,1,3,0,0,3

In [66]:
X=df_new.drop("price",axis=1) #apart from price, all columns hold in X variable
Y=df_new["price"] #output variable

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                              random_state=1)

In [68]:
X_train.shape,X_test.shape

((143, 14), (62, 14))

In [69]:
Y_train.shape,Y_test.shape

((143,), (62,))

In [70]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [71]:
X_train

array([[ 1.69785729,  0.02383412,  0.12469565, ...,  1.17275014,
        -0.14638501,  0.00639503],
       [-1.42488988,  0.02383412,  0.21756793, ...,  1.17275014,
        -0.14638501, -2.73707423],
       [-0.64420309, -1.38767531, -1.12908013, ..., -2.35784501,
        -0.14638501,  0.00639503],
       ...,
       [ 1.69785729,  0.7123753 ,  2.07501352, ...,  1.17275014,
        -0.14638501,  1.83537454],
       [ 0.91717049, -1.31882119, -1.03620785, ..., -2.35784501,
        -0.14638501,  0.92088479],
       [-0.64420309, -0.52699883, -0.38610189, ..., -0.59254744,
        -0.14638501,  0.00639503]])

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
lr=LinearRegression()

In [74]:
lr.fit(X_train,Y_train)

LinearRegression()

In [75]:
y_pred = lr.predict(X_test)

In [76]:
y_pred[:10]

array([ 6156.30873405,  6881.39391275,  5171.26920617,  6520.51014054,
        9093.39963824, 26361.27296732,  7457.92344044,   853.81331031,
        5152.19300699, 13525.47175298])

In [77]:
lr.score(X_train,Y_train)

0.850489309463496

In [78]:
lr.coef_

array([   58.5199306 ,    42.62344719,  1705.22158307,   911.904113  ,
        4054.4866814 ,  -469.6107472 ,  1948.51767416, -2768.17968401,
       -1251.27615463,  -177.68995089,  -148.91270542,  1057.82886344,
        2354.66996449,   307.4303196 ])

In [79]:
lr.score(X_test,Y_test)

0.7967454596734991

In [80]:
dict={'features':X.columns,'Slope':lr.coef_}
df1=pd.DataFrame(dict)
df1

             features        Slope
0           symboling    58.519931
1   normalized-losses    42.623447
2               width  1705.221583
3              height   911.904113
4         engine-size  4054.486681
5          horsepower  -469.610747
6            city-mpg  1948.517674
7         highway-mpg -2768.179684
8                make -1251.276155
9           fuel-type  -177.689951
10         body-style  -148.912705
11       drive-wheels  1057.828863
12    engine-location  2354.669964
13        engine-type   307.430320

In [81]:
from sklearn.linear_model import Lasso

In [82]:
for i in range(200,1001,50): #start=200 stop=1001-1=1000 step=+50
    #create the object of Lasso class , passing the value of lambda
    l1=Lasso(i) #first i=200 , next i=250 ......
    #automatic write formula RSS+i*sum(abs(all coef))
    #train the model with 70% data using Lasso class , use fit() inbuilt
    #method of Lasso class
    l1.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score
    print("Training Score : ",l1.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l1.score(X_test,Y_test))

Value of Lambda :  200
Training Score :  0.8410262816516455
Testing Score :  0.8111395722615142
Value of Lambda :  250
Training Score :  0.8385340173594726
Testing Score :  0.8105498997329942
Value of Lambda :  300
Training Score :  0.8354878961834389
Testing Score :  0.8094641048334433
Value of Lambda :  350
Training Score :  0.8319938320056115
Testing Score :  0.8079346980993205
Value of Lambda :  400
Training Score :  0.8284657641792199
Testing Score :  0.8061490778483928
Value of Lambda :  450
Training Score :  0.8249546529678113
Testing Score :  0.8041489036760304
Value of Lambda :  500
Training Score :  0.8210304998885254
Testing Score :  0.8017878944315399
Value of Lambda :  550
Training Score :  0.8166932955129319
Testing Score :  0.7990660335452213
Value of Lambda :  600
Training Score :  0.8119430443772861
Testing Score :  0.7959832844784963
Value of Lambda :  650
Training Score :  0.8067797434912503
Testing Score :  0.7925396011412089
Value of Lambda :  700
Training Score :  0.8018558303409655
Testing Score :  0.788982628108363
Value of Lambda :  750
Training Score :  0.7978566473416827
Testing Score :  0.7856542048320498
Value of Lambda :  800
Training Score :  0.7935816605078392
Testing Score :  0.7821357320480606
Value of Lambda :  850
Training Score :  0.7890308610369865
Testing Score :  0.7784272113835824
Value of Lambda :  900
Training Score :  0.7842042570823878
Testing Score :  0.7745286406360254
Value of Lambda :  950
Training Score :  0.7791274649239102
Testing Score :  0.7704701520045811
Value of Lambda :  1000
Training Score :  0.7754550114623461
Testing Score :  0.7681983507406608

In [83]:
l1.coef_

array([  -0.        ,    0.        , 1149.39028092,    0.        ,
       4149.53419025,    0.        ,   -0.        , -441.14217416,
         -0.        ,   -0.        ,   -0.        ,  376.53222035,
       1077.64509062,    0.        ])

In [84]:
df1['Slope_Lasso']=l1.coef_
df1

             features        Slope  Slope_Lasso
0           symboling    58.519931    -0.000000
1   normalized-losses    42.623447     0.000000
2               width  1705.221583  1149.390281
3              height   911.904113     0.000000
4         engine-size  4054.486681  4149.534190
5          horsepower  -469.610747     0.000000
6            city-mpg  1948.517674    -0.000000
7         highway-mpg -2768.179684  -441.142174
8                make -1251.276155    -0.000000
9           fuel-type  -177.689951    -0.000000
10         body-style  -148.912705    -0.000000
11       drive-wheels  1057.828863   376.532220
12    engine-location  2354.669964  1077.645091
13        engine-type   307.430320     0.000000

In [85]:
lasso_model = Lasso(alpha= 200)

In [86]:
lasso_model.fit(X_train, Y_train)

Lasso(alpha=200)

In [87]:
lasso_pred = lasso_model.predict(X_test)

In [88]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(Y_test, lasso_pred))
print("MSE :", mean_squared_error(Y_test, lasso_pred))
print("R² Score :", r2_score(Y_test, lasso_pred))

MAE : 2350.473190835319
MSE : 11380696.984090814
R² Score : 0.8111395722615142

In [89]:
from sklearn.linear_model import Ridge

In [90]:
for i in range(0,51): #start=0 stop=51-1=50 step=+1
    #create the object of Ridge means L2 and passing the value of lambda
    l2=Ridge(i)
    #train the model with 70% data using Ridge class , use fit() inbuilt
    #method of Ridge class
    l2.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score
    print("Training Score : ",l2.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l2.score(X_test,Y_test))

Value of Lambda :  0
Training Score :  0.850489309463496
Testing Score :  0.796745459673499
Value of Lambda :  1
Training Score :  0.8502458121760607
Testing Score :  0.7999229468389315
Value of Lambda :  2
Training Score :  0.8497608981834011
Testing Score :  0.8021793311303731
Value of Lambda :  3
Training Score :  0.8491864337627555
Testing Score :  0.8038967841553855
Value of Lambda :  4
Training Score :  0.8485710401808918
Testing Score :  0.8052507107945486
Value of Lambda :  5
Training Score :  0.8479340474587549
Testing Score :  0.8063381503980126
Value of Lambda :  6
Training Score :  0.8472846447934325
Testing Score :  0.8072198455487525
Value of Lambda :  7
Training Score :  0.846627874265068
Testing Score :  0.8079371174398748
Value of Lambda :  8
Training Score :  0.8459668111643571
Testing Score :  0.8085197380411502
Value of Lambda :  9
Training Score :  0.845303469621013
Testing Score :  0.8089900552586758
Value of Lambda :  10
Training Score :  0.8446392281399304
Testing Score :  0.8093653597999755
Value of Lambda :  11
Training Score :  0.8439750535958609
Testing Score :  0.8096593431593254
Value of Lambda :  12
Training Score :  0.8433116313861208
Testing Score :  0.8098830473171332
Value of Lambda :  13
Training Score :  0.8426494473384153
Testing Score :  0.8100455113109801
Value of Lambda :  14
Training Score :  0.841988842454038
Testing Score :  0.8101542272677273
Value of Lambda :  15
Training Score :  0.8413300511096681
Testing Score :  0.81021547138654
Value of Lambda :  16
Training Score :  0.8406732285304567
Testing Score :  0.8102345498801236
Value of Lambda :  17
Training Score :  0.8400184709613212
Testing Score :  0.8102159853463372
Value of Lambda :  18
Training Score :  0.839365830689585
Testing Score :  0.810163660365404
Value of Lambda :  19
Training Score :  0.8387153273430183
Testing Score :  0.8100809297307207
Value of Lambda :  20
Training Score :  0.8380669564432179
Testing Score :  0.8099707092612414
Value of Lambda :  21
Training Score :  0.8374206959090671
Testing Score :  0.8098355468550026
Value of Lambda :  22
Training Score :  0.8367765110138911
Testing Score :  0.8096776798908027
Value of Lambda :  23
Training Score :  0.8361343581674818
Testing Score :  0.8094990820080845
Value of Lambda :  24
Training Score :  0.8354941878000224
Testing Score :  0.8093015015332968
Value of Lambda :  25
Training Score :  0.8348559465566756
Testing Score :  0.8090864932728676
Value of Lambda :  26
Training Score :  0.8342195789613723
Testing Score :  0.808855444992426
Value of Lambda :  27
Training Score :  0.8335850286709234
Testing Score :  0.8086095996052777
Value of Lambda :  28
Training Score :  0.8329522394124671
Testing Score :  0.8083500738707374
Value of Lambda :  29
Training Score :  0.8323211556759682
Testing Score :  0.808077874234308
Value of Lambda :  30
Training Score :  0.8316917232172605
Testing Score :  0.8077939103125661
Value of Lambda :  31
Training Score :  0.8310638894146906
Testing Score :  0.8074990064258231
Value of Lambda :  32
Training Score :  0.8304376035128556
Testing Score :  0.80719391150383
Value of Lambda :  33
Training Score :  0.8298128167795293
Testing Score :  0.8068793076286825
Value of Lambda :  34
Training Score :  0.8291894825961431
Testing Score :  0.806555817430724
Value of Lambda :  35
Training Score :  0.8285675564977236
Testing Score :  0.8062240105147122
Value of Lambda :  36
Training Score :  0.8279469961747149
Testing Score :  0.8058844090626244
Value of Lambda :  37
Training Score :  0.8273277614463926
Testing Score :  0.8055374927345644
Value of Lambda :  38
Training Score :  0.8267098142134439
Testing Score :  0.8051837029690238
Value of Lambda :  39
Training Score :  0.8260931183956216
Testing Score :  0.8048234467672827
Value of Lambda :  40
Training Score :  0.8254776398590608
Testing Score :  0.8044571000332309
Value of Lambda :  41
Training Score :  0.8248633463368168
Testing Score :  0.8040850105287843
Value of Lambda :  42
Training Score :  0.8242502073453666
Testing Score :  0.803707500495879
Value of Lambda :  43
Training Score :  0.8236381940991779
Testing Score :  0.8033248689883975
Value of Lambda :  44
Training Score :  0.8230272794249422
Testing Score :  0.8029373939510214
Value of Lambda :  45
Training Score :  0.8224174376766741
Testing Score :  0.8025453340766753
Value of Lambda :  46
Training Score :  0.8218086446525629
Testing Score :  0.8021489304697593
Value of Lambda :  47
Training Score :  0.821200877514223
Testing Score :  0.8017484081385913
Value of Lambda :  48
Training Score :  0.8205941147087922
Testing Score :  0.8013439773372939
Value of Lambda :  49
Training Score :  0.8199883358941815
Testing Score :  0.8009358347746509
Value of Lambda :  50
Training Score :  0.8193835218676613
Testing Score :  0.800524164705157

In [91]:
l2.coef_

array([-178.67614837,   41.93458981, 1352.27576785,  690.52738187,
       2372.63214657,  781.08737444, -420.99588487, -846.78005321,
       -906.73937789, -557.04796008, -286.77533998,  984.19952342,
       1530.07575292,  414.10845604])

In [92]:
df1['Slope_Ridge']=l2.coef_
df1

             features        Slope  Slope_Lasso  Slope_Ridge
0           symboling    58.519931    -0.000000  -178.676148
1   normalized-losses    42.623447     0.000000    41.934590
2               width  1705.221583  1149.390281  1352.275768
3              height   911.904113     0.000000   690.527382
4         engine-size  4054.486681  4149.534190  2372.632147
5          horsepower  -469.610747     0.000000   781.087374
6            city-mpg  1948.517674    -0.000000  -420.995885
7         highway-mpg -2768.179684  -441.142174  -846.780053
8                make -1251.276155    -0.000000  -906.739378
9           fuel-type  -177.689951    -0.000000  -557.047960
10         body-style  -148.912705    -0.000000  -286.775340
11       drive-wheels  1057.828863   376.532220   984.199523
12    engine-location  2354.669964  1077.645091  1530.075753
13        engine-type   307.430320     0.000000   414.108456

In [93]:
ridge_model = Ridge(alpha= 12)

In [94]:
ridge_model.fit(X_train, Y_train)

Ridge(alpha=12)

In [95]:
ridge_pred = ridge_model.predict(X_test)

In [96]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(Y_test, ridge_pred))
print("MSE :", mean_squared_error(Y_test, ridge_pred))
print("R² Score :", r2_score(Y_test, ridge_pred))

MAE : 2349.1440150675758
MSE : 11456414.96173276
R² Score : 0.8098830473171332

In [97]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression"
    ],
    "MAE": [
        2465.395028223579,
        2346.9710123689783,
        2350.473190835319
    ],
    "MSE": [
        12262833.694863686,
        11433097.715870142,
        11380696.984090814
    ],
    "R2 Score": [
        0.7965006870725597,
        0.8102699924254559,
        0.8111395722615142
    ]
})

# Display the comparison table
comparison

               Model          MAE           MSE  R2 Score
0  Linear Regression  2465.395028  1.226283e+07  0.796501
1   Ridge Regression  2346.971012  1.143310e+07  0.810270
2   Lasso Regression  2350.473191  1.138070e+07  0.811140

In [98]:
comparison = pd.DataFrame({ "Actual": Y_test, "Predicted": y_pred })
comparison.head(10)

     Actual     Predicted
78     6669   6156.308734
97     7999   6881.393913
151    6338   5171.269206
44    10000   6520.510141
40    10295   9093.399638
67    25552  26361.272967
98     8249   7457.923440
18     5151    853.813310
152    6488   5152.193007
62    10245  13525.471753

In [99]:
from sklearn.metrics import mean_absolute_error

In [100]:
mae = mean_absolute_error(Y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 2460.3043475548525

In [101]:
from sklearn.metrics import mean_squared_error

In [102]:
mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 12248083.739912

In [103]:
from sklearn.metrics import r2_score

In [104]:
r2 = r2_score(Y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.7967454596734991

In [112]:
import math
rsme = math.sqrt(mae)
print("Root Mean Squared Error:", rsme)

Root Mean Squared Error: 49.6014550951366